name: Fetch Comments on Events

on:
  issue_comment:
    types: [created, edited, deleted]
  discussion_comment:
    types: [created, edited, deleted]

jobs:
  fetch_comments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch Comments
        uses: ./
        with:
          discussion_enable: 'true'
          category_id: 'DIC_kwDONhvWjc4ClfPP'  # å¯é€‰
          limit: '20' # å¯é€‰

      - name: Git config
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
  
      - name: Commit changes
        run: |
          cd output
          git add .
          git commit -m "ğŸ“¬ $(date +"%Yå¹´%mæœˆ%dæ—¥-%Hæ—¶%Måˆ†") GitHub Action æ¨é€"
          git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:comment
